Changes
Pool for bounded executions.
New "queued" status.
Logging fixes.
Code cleanup.
API tests.

diff --git a/contrib/poll b/contrib/poll
--- a/contrib/poll
+++ b/contrib/poll
@@ -8,13 +8,17 @@ JOB=$2
 cnt=0
 while true; do
   status_line=$(curl -s "$MULO/status/$JOB")
-  read status rc <<< "$status_line"
+  read -r status rc <<< "$status_line"
   out=$(curl -sr $cnt- "$MULO/output/$JOB")
   len=${#out}
   cnt=$((cnt + len))
   echo -n "$out"
-  if [ "$status" == "running" ]; then
+  if [ "$status" == "queued" ] || [ "$status" == "running" ]; then
     sleep 1
+  elif [ "$status" == "failed" ]; then
+    echo
+    echo "Job $JOB failed: ${status_line:7}"
+    exit 100
   else
     echo
     echo "Job $JOB completed with code $rc"
diff --git a/contrib/poll-auth b/contrib/poll-auth
--- a/contrib/poll-auth
+++ b/contrib/poll-auth
@@ -15,8 +15,12 @@ while true; do
   len=${#out}
   cnt=$((cnt + len))
   echo -n "$out"
-  if [ "$status" == "running" ]; then
+  if [ "$status" == "queued" ] || [ "$status" == "running" ]; then
     sleep 1
+  elif [ "$status" == "failed" ]; then
+    echo
+    echo "Job $JOB failed: ${status_line:7}"
+    exit 100
   else
     echo
     echo "Job $JOB completed with code $rc"
